name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Chechout
        with:
          fetch-depth: 0

      - shell: bash
        name: Run release script
        run: sh ./.github/workflows/sh/release.sh
        env:
          TRACKER_HOST: 'https://api.tracker.yandex.net'
          TRACKER_ORG_ID: ${{secrets.TRACKER_ORG_ID}}
          TRACKER_QUEUE: 'TMP'
          TRACKER_TOKEN: ${{secrets.TRACKER_TOKEN}}
          TRACKER_UNIQUE_PREFIX: 'savinovskikh'

      - shell: bash
        name: Run artifact script
        run: sh ./.github/workflows/sh/artifact.sh
        env:
          TRACKER_HOST: 'https://api.tracker.yandex.net'
          TRACKER_ORG_ID: ${{secrets.TRACKER_ORG_ID}}
          TRACKER_QUEUE: 'TMP'
          TRACKER_TOKEN: ${{secrets.TRACKER_TOKEN}}
          TRACKER_UNIQUE_PREFIX: 'savinovskikh'

      - shell: bash
        name: Run test script
        run: sh ./.github/workflows/sh/runTests.sh
        env:
          TRACKER_HOST: 'https://api.tracker.yandex.net'
          TRACKER_ORG_ID: ${{secrets.TRACKER_ORG_ID}}
          TRACKER_QUEUE: 'TMP'
          TRACKER_TOKEN: ${{secrets.TRACKER_TOKEN}}
          TRACKER_UNIQUE_PREFIX: 'savinovskikh'